"""Add contributor submissions

Revision ID: 69cc9fd1685e
Revises: 6da4b8e193d8
Create Date: 2026-06-18 03:13:13.634063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69cc9fd1685e'
down_revision = '6da4b8e193d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contributor_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('proposed_code', sa.String(length=16), nullable=True),
    sa.Column('finalized_code', sa.String(length=16), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('release', sa.DateTime(), nullable=False),
    sa.Column('experiment', sa.Text(), nullable=False),
    sa.Column('pub_doi', sa.String(length=64), nullable=True),
    sa.Column('struct_doi', sa.String(length=64), nullable=True),
    sa.Column('citation', sa.String(length=1024), nullable=True),
    sa.Column('authors', sa.Text(), nullable=False),
    sa.Column('input_type', sa.String(length=16), nullable=False),
    sa.Column('original_smiles', sa.Text(), nullable=True),
    sa.Column('cleaned_smiles', sa.Text(), nullable=False),
    sa.Column('topology', sa.String(length=1), nullable=False),
    sa.Column('sequence', sa.String(length=1024), nullable=True),
    sa.Column('residue_data_json', sa.Text(), nullable=False),
    sa.Column('warnings_json', sa.Text(), nullable=True),
    sa.Column('structure_image_path', sa.Text(), nullable=True),
    sa.Column('residue_image_path', sa.Text(), nullable=True),
    sa.Column('staged_cif_path', sa.Text(), nullable=True),
    sa.Column('original_cif_filename', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['contributor_id'], ['contributor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_submission_contributor_id'), ['contributor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_submission_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submission_status'))
        batch_op.drop_index(batch_op.f('ix_submission_contributor_id'))

    op.drop_table('submission')
    # ### end Alembic commands ###
