"""Add contributor accounts

Revision ID: 6da4b8e193d8
Revises: 7b2e83c19eb3
Create Date: 2026-06-18 02:50:19.888851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6da4b8e193d8'
down_revision = '7b2e83c19eb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contributor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('institution', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contributor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contributor_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_contributor_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contributor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contributor_username'))
        batch_op.drop_index(batch_op.f('ix_contributor_email'))

    op.drop_table('contributor')
    # ### end Alembic commands ###
