"""Baseline existing schema

Revision ID: 7b2e83c19eb3
Revises: 
Create Date: 2026-06-18 02:38:53.879274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b2e83c19eb3'
down_revision = '85c558bd9870'
branch_labels = None
depends_on = None


def _has_table(name):
    return sa.inspect(op.get_bind()).has_table(name)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # This baseline may run against a live database whose existing schema
    # is already present but stamped with legacy revision 85c558bd9870.
    # Only create baseline tables when they are missing.
    if not _has_table('author'):
        op.create_table('author',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('first_name', sa.Text(), nullable=True),
        sa.Column('last_name', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    if not _has_table('peptoid'):
        op.create_table('peptoid',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('code', sa.String(length=16), nullable=True),
        sa.Column('title', sa.Text(), nullable=True),
        sa.Column('release', sa.DateTime(), nullable=True),
        sa.Column('experiment', sa.Text(), nullable=True),
        sa.Column('pub_doi', sa.String(length=64), nullable=True),
        sa.Column('struct_doi', sa.String(length=64), nullable=True),
        sa.Column('citation', sa.String(length=1024), nullable=True),
        sa.Column('topology', sa.String(length=1), nullable=True),
        sa.Column('sequence', sa.String(length=1024), nullable=True),
        sa.Column('n_term', sa.String(length=32), nullable=True),
        sa.Column('c_term', sa.String(length=32), nullable=True),
        sa.Column('cyclization_points', sa.String(length=8), nullable=True),
        sa.Column('struct_smiles', sa.String(length=128), nullable=True),
        sa.Column('refcode', sa.String(length=6), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code')
        )
    if not _has_table('residue'):
        op.create_table('residue',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('long_name', sa.Text(), nullable=True),
        sa.Column('short_name', sa.Text(), nullable=True),
        sa.Column('pep_type', sa.Text(), nullable=True),
        sa.Column('monomer_structure', sa.Text(), nullable=True),
        sa.Column('SMILES', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    if not _has_table('peptoid-author'):
        op.create_table('peptoid-author',
        sa.Column('peptoid_id', sa.String(length=16), nullable=True),
        sa.Column('author_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
        sa.ForeignKeyConstraint(['peptoid_id'], ['peptoid.code'], )
        )
    if not _has_table('peptoid-residue'):
        op.create_table('peptoid-residue',
        sa.Column('peptoid_id', sa.String(length=16), nullable=True),
        sa.Column('residue_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['peptoid_id'], ['peptoid.code'], ),
        sa.ForeignKeyConstraint(['residue_id'], ['residue.id'], )
        )
    # ### end Alembic commands ###


def downgrade():
    # This compatibility baseline may represent tables that already existed
    # in the live database before Alembic migration files were restored.
    # Do not drop legacy/public data on downgrade.
    pass
